<?php
/**
 * Created by PhpStorm.
 * User: ASUS
 * Date: 2019/10/14
 * Time: 11:18
 */

namespace app\admin\controller;


use think\Controller;
use think\Session;

class Base  extends Controller
{ //验证是否登录  init是相当于类的公共方法，要执行下面的方法都会先执行这个验证
   public function _initialize()
   {
       parent::_initialize(); // TODO: Change the autogenerated stub
       if(!Session::has('user')){
           $this->error('请先登录','admin/login/index');//tp中提供的跳转页面的方法
           exit();
       }
   }

}