<?php
/**
 * Created by PhpStorm.
 * User: ASUS
 * Date: 2019/10/11
 * Time: 11:07
 */

namespace app\admin\controller;


use think\Controller;
use think\Db;

class Goods extends Base
{    public function _initialize()
{
    parent::_initialize(); // TODO: Change the autogenerated stub
}

    public function openinsert(){
        $cate=Db::table('categoods')->order('cid','asc')->select();
        $this->assign('cate',$cate);//挂载数据,页面中用name里面访问变量
     return $this->fetch();
}
    public function insert(){
        if(!$this->request->isPost()){
            return json([
                'code'=>404,
                "msg"=>"请求方式不正确"
            ]);
        }
        $data=input('post.');
        $data['gbanner']=substr($data['gbanner'],0,-1);
        $validate=validate('Goods');
        if(!$validate->scene('insert')->check($data)){
            return json([
                'code'=>404,
                'msg'=>$validate->getError()
            ]);
        }
        $data['create_time']=date('Y-m-d H:i:s');
        date_default_timezone_set('PRC');
        $res=Db::table('goods')->insert($data);
        if($res>0){
            return json([
                'code'=>0,
                'msg'=>"恭喜您,插入成功",
            ]);
        }else{
            return json([
                'code'=>404,
                'msg'=>"插入失败"
            ]);
        }
    }
    //查看商品开页面
    public function openselect(){
        $cate=Db::table('categoods')->select();
        $this->assign('cate',$cate);
        return $this->fetch();
  }
    //查看商品
    public function select(){
        //给前台返回的数据：总数。当前的页码的数据select* from goods order by gid limit offset length
        $qs=input('get.');
//        dump($qs);
//        $cid=$qs['cid'];
//        $min=$qs['sprice_min'];
//        $max=$qs['sprice_max'];
//        $name=$qs['gname'];
        $where=[];
        if(isset($qs['cid'])&&!empty($qs['cid'])){
            $where['cid']=$qs['cid'];
        }
        if(isset($qs['sprice_min'])&&!empty($qs['sprice_min'])&&isset($qs['sprice_max'])&&!empty($qs['sprice_max'])&&$qs['sprice_max']>$qs['sprice_min']){
            $where['sprice']=['between',[$qs['sprice_min'],$qs['sprice_max']]];
        }
        if(isset($qs['gname'])&&!empty($qs['gname'])){
            $where['gname']=['like',"%{$qs['gname']}%"];
        }
        $page=$qs['page'];
        $limit=$qs['limit'];
//        $offset=($page-1)*$limit;//可以直接用page分页，也可以设置起始的下标$offset
            $count=Db::table('goods')->where($where)->count();//tp中获取总数的count方式
            $data=Db::table('goods')->where($where)->page($page,$limit)->select();
        //搜索条件 ：默认没有，点击搜索才有，点击之后不管有没有值字段都有
        if($count>0){
            return json([
                'code'=>0,
                'msg'=>"恭喜您,查找成功",
                'count'=>$count,
                'data'=>$data
            ]);
        }
    }

}