<?php
/**
 * Created by PhpStorm.
 * User: ASUS
 * Date: 2019/10/14
 * Time: 16:00
 */

namespace app\index\controller;
use think\Controller;
use think\Db;

class Base extends Controller
{
    protected function _initialize()
    {   //处理公共部分的逻辑，因为控制器中不能引入控制器，但是这里有些页面都需要处理公共头部逻辑，所以用继承，又因为不是每个页面都需要头部，所有让base继承controller，在让需要公共的部分继承base
        parent::_initialize(); // TODO: Change the autogenerated stub
        $nav=Db::table('nav')->order('nsort','asc')->select();
        $this->assign('nav',$nav);
    }

}